[openshell]
version = 2

[openshell.gateway]
compute_driver = "vm"

[openshell.drivers.vm]
default_image = "openenv-openshell-prerequisites:0.0.116"
bootstrap_image = "openenv-openshell-prerequisites:0.0.116"
