"""Bounded, explicitly provisioned CI entry point for the I2/I3 suites."""

from __future__ import annotations

import logging
import os
import signal
import subprocess
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
from xml.etree import ElementTree as ET

from tests.integration._runtime import interrupt

SUITES = (
    ("test_openenv_client.py", "OPENENV_OPENSHELL_ECHO_IMAGE_ID", 2),
    ("test_filesystem_security.py", "OPENENV_OPENSHELL_FILESYSTEM_IMAGE_ID", 1),
    ("test_network_security.py", "OPENENV_OPENSHELL_NETWORK_IMAGE_ID", 2),
)
SUITE_TIMEOUT_S = 600
CLEANUP_GRACE_S = 180
MISCONFIGURED = 2
TIMED_OUT = 124
LOGGER = logging.getLogger(__name__)


def run_bounded(argv: list[str], env: dict[str, str]) -> int:
    """Give pytest a catchable interruption and bounded time to unwind."""
    # Fixed argv only; never run workflow inputs through a shell.
    process = subprocess.Popen(argv, env=env, start_new_session=True)  # noqa: S603
    try:
        return process.wait(timeout=SUITE_TIMEOUT_S)
    except subprocess.TimeoutExpired:
        # Keep subprocess arguments out of CI diagnostics.
        LOGGER.error(  # noqa: TRY400
            "E2E suite timed out; requesting fixture cleanup."
        )
        return TIMED_OUT
    finally:
        if process.poll() is None:
            os.killpg(process.pid, signal.SIGTERM)
            try:
                process.wait(timeout=CLEANUP_GRACE_S)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
                process.wait()
                LOGGER.error(  # noqa: TRY400 - Fixed diagnostics, no subprocess argv.
                    "E2E forced termination; inspect owned sandboxes."
                )


def report_passed(path: Path, expected: int) -> bool:
    """Reject empty, skipped, or incomplete runs even if pytest returns zero."""
    # Report is generated by our own pytest subprocess, never downloaded XML.
    root = ET.parse(path).getroot()  # noqa: S314
    cases = root.findall(".//testcase")
    return len(cases) == expected and all(
        not any(case.find(tag) is not None for tag in ("skipped", "failure", "error"))
        for case in cases
    )


def main() -> int:
    """Run each suite sequentially with its explicitly selected image."""
    required = [image for _, image, _ in SUITES] + ["OPENSHELL_GATEWAY"]
    missing = [name for name in required if not os.environ.get(name)]
    if missing:
        LOGGER.error("Runtime CI not provisioned: set %s.", ", ".join(missing))
        return MISCONFIGURED
    with TemporaryDirectory(prefix="openshell-ci-") as directory:
        for filename, image_variable, expected in SUITES:
            report = Path(directory) / f"{filename}.xml"
            env = dict(os.environ)
            env["OPENENV_OPENSHELL_ECHO_IMAGE_ID"] = env[image_variable]
            argv = [
                sys.executable,
                "-m",
                "pytest",
                "-m",
                "integration",
                "--no-cov",
                "-v",
                "-rA",
                "--show-capture=all",
                f"--junitxml={report}",
                f"tests/integration/{filename}",
            ]
            result = run_bounded(argv, env)
            if result:
                return result
            if not report_passed(report, expected):
                LOGGER.error("E2E report incomplete or skipped; CI acceptance failed.")
                return 1
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    signal.signal(signal.SIGTERM, interrupt)
    sys.exit(main())
